/**
 * Unified alias map for timezone resolution.
 *
 * Maps user-friendly input strings to IANA timezone identifiers.
 * Keys are stored uppercase for case-insensitive matching.
 *
 * Covers:
 * - Standard timezone abbreviations (EST, CET, JST, etc.)
 * - Common city and region names that differ from or aren't in the IANA list
 * - Airport/short codes (NYC, LAX, etc.)
 * - Informal and alternate names
 */
export const TIMEZONE_ALIASES: ReadonlyMap<string, string> = new Map([
  // ─── North America abbreviations ───────────────────────────────────────────
  ["EST", "America/New_York"],
  ["EDT", "America/New_York"],
  ["ET", "America/New_York"],
  ["EASTERN", "America/New_York"],
  ["CST", "America/Chicago"],
  ["CDT", "America/Chicago"],
  ["CT", "America/Chicago"],
  ["CENTRAL", "America/Chicago"],
  ["MST", "America/Denver"],
  ["MDT", "America/Denver"],
  ["MT", "America/Denver"],
  ["MOUNTAIN", "America/Denver"],
  ["PST", "America/Los_Angeles"],
  ["PDT", "America/Los_Angeles"],
  ["PT", "America/Los_Angeles"],
  ["PACIFIC", "America/Los_Angeles"],
  ["AKST", "America/Anchorage"],
  ["AKDT", "America/Anchorage"],
  ["HST", "Pacific/Honolulu"],
  ["AST", "America/Halifax"],
  ["ADT", "America/Halifax"],
  ["NST", "America/St_Johns"],
  ["NDT", "America/St_Johns"],

  // ─── North America city/short codes ────────────────────────────────────────
  ["NYC", "America/New_York"],
  ["NEW YORK", "America/New_York"],
  ["NEW YORK CITY", "America/New_York"],
  ["LAX", "America/Los_Angeles"],
  ["LOS ANGELES", "America/Los_Angeles"],
  ["LA", "America/Los_Angeles"],
  ["SFO", "America/Los_Angeles"],
  ["SAN FRANCISCO", "America/Los_Angeles"],
  ["SF", "America/Los_Angeles"],
  ["SEA", "America/Los_Angeles"],
  ["ORD", "America/Chicago"],
  ["CHICAGO", "America/Chicago"],
  ["CHI", "America/Chicago"],
  ["DFW", "America/Chicago"],
  ["DALLAS", "America/Chicago"],
  ["ATX", "America/Chicago"],
  ["AUS", "America/Chicago"],
  ["AUSTIN", "America/Chicago"],
  ["HOU", "America/Chicago"],
  ["HOUSTON", "America/Chicago"],
  ["DEN", "America/Denver"],
  ["DENVER", "America/Denver"],
  ["PHX", "America/Phoenix"],
  ["PHOENIX", "America/Phoenix"],
  ["ARIZONA", "America/Phoenix"],
  ["ATL", "America/New_York"],
  ["ATLANTA", "America/New_York"],
  ["BOS", "America/New_York"],
  ["BOSTON", "America/New_York"],
  ["MIA", "America/New_York"],
  ["MIAMI", "America/New_York"],
  ["DC", "America/New_York"],
  ["WASHINGTON", "America/New_York"],
  ["WASHINGTON DC", "America/New_York"],
  ["YYZ", "America/Toronto"],
  ["TORONTO", "America/Toronto"],
  ["YUL", "America/Toronto"],
  ["MONTREAL", "America/Toronto"],
  ["YVR", "America/Vancouver"],
  ["VANCOUVER", "America/Vancouver"],
  ["MEX", "America/Mexico_City"],
  ["MEXICO CITY", "America/Mexico_City"],
  ["MEXICO", "America/Mexico_City"],
  ["HAV", "America/Havana"],
  ["HAVANA", "America/Havana"],
  ["CUBA", "America/Havana"],

  // ─── Europe abbreviations ───────────────────────────────────────────────────
  ["GMT", "Europe/London"],
  ["UTC", "Etc/UTC"],
  ["BST", "Europe/London"],
  ["WET", "Europe/Lisbon"],
  ["WEST", "Europe/Lisbon"],
  ["CET", "Europe/Paris"],
  ["CEST", "Europe/Paris"],
  ["EET", "Europe/Helsinki"],
  ["EEST", "Europe/Helsinki"],
  ["MSK", "Europe/Moscow"],
  ["IST", "Europe/Dublin"],

  // ─── Europe city/short codes ────────────────────────────────────────────────
  ["LHR", "Europe/London"],
  ["LONDON", "Europe/London"],
  ["LGW", "Europe/London"],
  ["UK", "Europe/London"],
  ["ENGLAND", "Europe/London"],
  ["CDG", "Europe/Paris"],
  ["PARIS", "Europe/Paris"],
  ["FRANCE", "Europe/Paris"],
  ["BERLIN", "Europe/Berlin"],
  ["GERMANY", "Europe/Berlin"],
  ["FRA", "Europe/Berlin"],
  ["AMS", "Europe/Amsterdam"],
  ["AMSTERDAM", "Europe/Amsterdam"],
  ["NETHERLANDS", "Europe/Amsterdam"],
  ["MAD", "Europe/Madrid"],
  ["MADRID", "Europe/Madrid"],
  ["SPAIN", "Europe/Madrid"],
  ["BCN", "Europe/Madrid"],
  ["BARCELONA", "Europe/Madrid"],
  ["FCO", "Europe/Rome"],
  ["ROME", "Europe/Rome"],
  ["ITALY", "Europe/Rome"],
  ["MXP", "Europe/Rome"],
  ["MILAN", "Europe/Rome"],
  ["ZRH", "Europe/Zurich"],
  ["ZURICH", "Europe/Zurich"],
  ["SWITZERLAND", "Europe/Zurich"],
  ["VIE", "Europe/Vienna"],
  ["VIENNA", "Europe/Vienna"],
  ["AUSTRIA", "Europe/Vienna"],
  ["ARN", "Europe/Stockholm"],
  ["STOCKHOLM", "Europe/Stockholm"],
  ["SWEDEN", "Europe/Stockholm"],
  ["OSL", "Europe/Oslo"],
  ["OSLO", "Europe/Oslo"],
  ["NORWAY", "Europe/Oslo"],
  ["CPH", "Europe/Copenhagen"],
  ["COPENHAGEN", "Europe/Copenhagen"],
  ["DENMARK", "Europe/Copenhagen"],
  ["HEL", "Europe/Helsinki"],
  ["HELSINKI", "Europe/Helsinki"],
  ["FINLAND", "Europe/Helsinki"],
  ["WAW", "Europe/Warsaw"],
  ["WARSAW", "Europe/Warsaw"],
  ["POLAND", "Europe/Warsaw"],
  ["PRG", "Europe/Prague"],
  ["PRAGUE", "Europe/Prague"],
  ["BUD", "Europe/Budapest"],
  ["BUDAPEST", "Europe/Budapest"],
  ["ATH", "Europe/Athens"],
  ["ATHENS", "Europe/Athens"],
  ["GREECE", "Europe/Athens"],
  ["LIS", "Europe/Lisbon"],
  ["LISBON", "Europe/Lisbon"],
  ["PORTUGAL", "Europe/Lisbon"],
  ["BRU", "Europe/Brussels"],
  ["BRUSSELS", "Europe/Brussels"],
  ["BELGIUM", "Europe/Brussels"],
  ["GVA", "Europe/Zurich"],
  ["GENEVA", "Europe/Zurich"],
  ["SVO", "Europe/Moscow"],
  ["MOSCOW", "Europe/Moscow"],
  ["RUSSIA", "Europe/Moscow"],
  ["IST-EU", "Europe/Istanbul"],
  ["ISTANBUL", "Europe/Istanbul"],
  ["TURKEY", "Europe/Istanbul"],
  ["DUBLIN", "Europe/Dublin"],
  ["IRELAND", "Europe/Dublin"],

  // ─── Asia abbreviations ─────────────────────────────────────────────────────
  ["IST-IN", "Asia/Kolkata"],
  ["INDIA", "Asia/Kolkata"],
  ["JST", "Asia/Tokyo"],
  ["KST", "Asia/Seoul"],
  ["CST-CN", "Asia/Shanghai"],
  ["HKT", "Asia/Hong_Kong"],
  ["SGT", "Asia/Singapore"],
  ["PHT", "Asia/Manila"],
  ["ICT", "Asia/Bangkok"],
  ["WIB", "Asia/Jakarta"],
  ["GST", "Asia/Dubai"],
  ["PKT", "Asia/Karachi"],
  ["BDT", "Asia/Dhaka"],
  ["NPT", "Asia/Kathmandu"],
  ["MMT", "Asia/Rangoon"],
  ["THA", "Asia/Bangkok"],

  // ─── Asia city/short codes ──────────────────────────────────────────────────
  ["NRT", "Asia/Tokyo"],
  ["TOKYO", "Asia/Tokyo"],
  ["JAPAN", "Asia/Tokyo"],
  ["ICN", "Asia/Seoul"],
  ["SEOUL", "Asia/Seoul"],
  ["KOREA", "Asia/Seoul"],
  ["PVG", "Asia/Shanghai"],
  ["SHANGHAI", "Asia/Shanghai"],
  ["BEIJING", "Asia/Shanghai"],
  ["CHINA", "Asia/Shanghai"],
  ["HKG", "Asia/Hong_Kong"],
  ["HONG KONG", "Asia/Hong_Kong"],
  ["SIN", "Asia/Singapore"],
  ["SINGAPORE", "Asia/Singapore"],
  ["BOM", "Asia/Kolkata"],
  ["MUMBAI", "Asia/Kolkata"],
  ["DEL", "Asia/Kolkata"],
  ["DELHI", "Asia/Kolkata"],
  ["NEW DELHI", "Asia/Kolkata"],
  ["BLR", "Asia/Kolkata"],
  ["BANGALORE", "Asia/Kolkata"],
  ["MNL", "Asia/Manila"],
  ["MANILA", "Asia/Manila"],
  ["PHILIPPINES", "Asia/Manila"],
  ["BKK", "Asia/Bangkok"],
  ["BANGKOK", "Asia/Bangkok"],
  ["THAILAND", "Asia/Bangkok"],
  ["CGK", "Asia/Jakarta"],
  ["JAKARTA", "Asia/Jakarta"],
  ["INDONESIA", "Asia/Jakarta"],
  ["KUL", "Asia/Kuala_Lumpur"],
  ["KUALA LUMPUR", "Asia/Kuala_Lumpur"],
  ["MALAYSIA", "Asia/Kuala_Lumpur"],
  ["DXB", "Asia/Dubai"],
  ["DUBAI", "Asia/Dubai"],
  ["UAE", "Asia/Dubai"],
  ["DOH", "Asia/Qatar"],
  ["DOHA", "Asia/Qatar"],
  ["QATAR", "Asia/Qatar"],
  ["RUH", "Asia/Riyadh"],
  ["RIYADH", "Asia/Riyadh"],
  ["SAUDI ARABIA", "Asia/Riyadh"],
  ["TLV", "Asia/Jerusalem"],
  ["TEL AVIV", "Asia/Jerusalem"],
  ["ISRAEL", "Asia/Jerusalem"],
  ["KHI", "Asia/Karachi"],
  ["KARACHI", "Asia/Karachi"],
  ["PAKISTAN", "Asia/Karachi"],
  ["DAC", "Asia/Dhaka"],
  ["DHAKA", "Asia/Dhaka"],
  ["BANGLADESH", "Asia/Dhaka"],
  ["KTM", "Asia/Kathmandu"],
  ["KATHMANDU", "Asia/Kathmandu"],
  ["NEPAL", "Asia/Kathmandu"],

  // ─── Africa city/short codes ────────────────────────────────────────────────
  ["JNB", "Africa/Johannesburg"],
  ["JOHANNESBURG", "Africa/Johannesburg"],
  ["SOUTH AFRICA", "Africa/Johannesburg"],
  ["NBO", "Africa/Nairobi"],
  ["NAIROBI", "Africa/Nairobi"],
  ["KENYA", "Africa/Nairobi"],
  ["CAI", "Africa/Cairo"],
  ["CAIRO", "Africa/Cairo"],
  ["EGYPT", "Africa/Cairo"],
  ["LOS", "Africa/Lagos"],
  ["LAGOS", "Africa/Lagos"],
  ["NIGERIA", "Africa/Lagos"],
  ["ACC", "Africa/Accra"],
  ["ACCRA", "Africa/Accra"],
  ["GHANA", "Africa/Accra"],
  ["CMN", "Africa/Casablanca"],
  ["CASABLANCA", "Africa/Casablanca"],
  ["MOROCCO", "Africa/Casablanca"],
  ["ADD", "Africa/Addis_Ababa"],
  ["ADDIS ABABA", "Africa/Addis_Ababa"],
  ["ETHIOPIA", "Africa/Addis_Ababa"],
  ["DAR ES SALAAM", "Africa/Dar_es_Salaam"],
  ["TANZANIA", "Africa/Dar_es_Salaam"],

  // ─── Oceania abbreviations ───────────────────────────────────────────────────
  ["AEST", "Australia/Sydney"],
  ["AEDT", "Australia/Sydney"],
  ["ACST", "Australia/Darwin"],
  ["ACDT", "Australia/Adelaide"],
  ["AWST", "Australia/Perth"],
  ["NZST", "Pacific/Auckland"],
  ["NZDT", "Pacific/Auckland"],

  // ─── Oceania city/short codes ────────────────────────────────────────────────
  ["SYD", "Australia/Sydney"],
  ["SYDNEY", "Australia/Sydney"],
  ["MEL", "Australia/Melbourne"],
  ["MELBOURNE", "Australia/Melbourne"],
  ["BNE", "Australia/Brisbane"],
  ["BRISBANE", "Australia/Brisbane"],
  ["PER", "Australia/Perth"],
  ["PERTH", "Australia/Perth"],
  ["ADL", "Australia/Adelaide"],
  ["ADELAIDE", "Australia/Adelaide"],
  ["AUSTRALIA", "Australia/Sydney"],
  ["AKL", "Pacific/Auckland"],
  ["AUCKLAND", "Pacific/Auckland"],
  ["NEW ZEALAND", "Pacific/Auckland"],
  ["NZ", "Pacific/Auckland"],
  ["FIJI", "Pacific/Fiji"],
  ["HAWAII", "Pacific/Honolulu"],

  // ─── South America city/short codes ─────────────────────────────────────────
  ["GRU", "America/Sao_Paulo"],
  ["SAO PAULO", "America/Sao_Paulo"],
  ["BRAZIL", "America/Sao_Paulo"],
  ["GIG", "America/Sao_Paulo"],
  ["RIO", "America/Sao_Paulo"],
  ["RIO DE JANEIRO", "America/Sao_Paulo"],
  ["EZE", "America/Argentina/Buenos_Aires"],
  ["BUENOS AIRES", "America/Argentina/Buenos_Aires"],
  ["ARGENTINA", "America/Argentina/Buenos_Aires"],
  ["SCL", "America/Santiago"],
  ["SANTIAGO", "America/Santiago"],
  ["CHILE", "America/Santiago"],
  ["BOG", "America/Bogota"],
  ["BOGOTA", "America/Bogota"],
  ["COLOMBIA", "America/Bogota"],
  ["LIM", "America/Lima"],
  ["LIMA", "America/Lima"],
  ["PERU", "America/Lima"],
]);
